// <auto-generated />
using System;
using APIFurnitureCRM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIFurnitureCRM.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251112224633_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("APIFurnitureCRM.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_клиента");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT")
                        .HasColumnName("Адрес");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ФИО");

                    b.Property<long>("Phone")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Номер_телефона");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("Дата_регистрации");

                    b.HasKey("Id");

                    b.ToTable("Клиент");
                });

            modelBuilder.Entity("APIFurnitureCRM.Models.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Артикул_сырья");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Наименование_материала");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Количество_в_наличии");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("Единица_измерения");

                    b.HasKey("MaterialId");

                    b.ToTable("Сырьё", null, t =>
                        {
                            t.HasCheckConstraint("CK_Сырьё_КоличествоВНаличии", "Количество_в_наличии >= 0");
                        });
                });

            modelBuilder.Entity("APIFurnitureCRM.Models.MaterialOrder", b =>
                {
                    b.Property<int>("MaterialOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Номер_заказа");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Артикул_сырья");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("Дата_заказа");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Количество");

                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_оформляющего_сотрудника");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Статус");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Поставщик");

                    b.HasKey("MaterialOrderId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("StaffId");

                    b.ToTable("Заказ_сырья", null, t =>
                        {
                            t.HasCheckConstraint("CK_ЗаказСырья_ДатаЗаказа", "Дата_заказа <= CURRENT_DATE");

                            t.HasCheckConstraint("CK_ЗаказСырья_Количество", "Количество >= 1");

                            t.HasCheckConstraint("CK_ЗаказСырья_Статус", "Статус IN ('Ожидает поставки', 'Доставлен', 'Отменен')");
                        });
                });

            modelBuilder.Entity("APIFurnitureCRM.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Номер_заказа");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_клиента");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("Дата_выполнения");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("Дата_оформления");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Артикул_товара");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Количество");

                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_оформляющего_сотрудника");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Статус_заказа");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Итоговая_стоимость");

                    b.HasKey("OrderId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StaffId");

                    b.ToTable("Заказ", null, t =>
                        {
                            t.HasCheckConstraint("CK_Заказ_ДатаОформления", "Дата_оформления <= CURRENT_DATE");

                            t.HasCheckConstraint("CK_Заказ_ДатыВыполнения", "Дата_выполнения IS NULL OR Дата_выполнения >= Дата_оформления");

                            t.HasCheckConstraint("CK_Заказ_ИтоговаяСтоимость", "Итоговая_стоимость > 0");

                            t.HasCheckConstraint("CK_Заказ_Количество", "Количество >= 1");

                            t.HasCheckConstraint("CK_Заказ_СтатусЗаказа", "Статус_заказа IN ('В обработке', 'В производстве', 'Выполнен', 'Отменен')");
                        });
                });

            modelBuilder.Entity("APIFurnitureCRM.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Артикул_товара");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Категория");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Цвет");

                    b.Property<string>("Dimensions")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Размеры");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Наименование");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Стоимость");

                    b.HasKey("ProductId");

                    b.ToTable("Номенклатура", null, t =>
                        {
                            t.HasCheckConstraint("CK_Номенклатура_Категория", "Категория IN ('Мебель для дома', 'Офисная мебель', 'Кухонная мебель', 'Детская мебель', 'Мягкая мебель', 'Корпусная мебель', 'Спальная мебель', 'Мебель для ванной')");

                            t.HasCheckConstraint("CK_Номенклатура_Стоимость", "Стоимость > 0");
                        });
                });

            modelBuilder.Entity("APIFurnitureCRM.Models.Specification", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Артикул_товара");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Артикул_сырья")
                        .HasAnnotation("Relational:JsonPropertyName", "MaterialId");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Количество");

                    b.HasKey("ProductId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("Спецификация_номенклатуры", null, t =>
                        {
                            t.HasCheckConstraint("CK_СпецификацияНоменклатуры_Количество", "Количество >= 1");
                        });
                });

            modelBuilder.Entity("APIFurnitureCRM.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_сотрудника");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("ФИО");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Должность");

                    b.HasKey("StaffId");

                    b.ToTable("Персонал");
                });

            modelBuilder.Entity("APIFurnitureCRM.Models.UserAccount", b =>
                {
                    b.Property<int>("UserAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_учетной_записи");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Пароль");

                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_сотрудника");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Логин");

                    b.HasKey("UserAccountId");

                    b.HasIndex("StaffId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Учетные_записи_пользователей");
                });

            modelBuilder.Entity("APIFurnitureCRM.Models.MaterialOrder", b =>
                {
                    b.HasOne("APIFurnitureCRM.Models.Material", "Material")
                        .WithMany("MaterialOrders")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIFurnitureCRM.Models.Staff", "Staff")
                        .WithMany("MaterialOrders")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("APIFurnitureCRM.Models.Order", b =>
                {
                    b.HasOne("APIFurnitureCRM.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIFurnitureCRM.Models.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIFurnitureCRM.Models.Staff", "Staff")
                        .WithMany("Orders")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Product");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("APIFurnitureCRM.Models.Specification", b =>
                {
                    b.HasOne("APIFurnitureCRM.Models.Material", "Material")
                        .WithMany("Specifications")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIFurnitureCRM.Models.Product", "Product")
                        .WithMany("Specifications")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("APIFurnitureCRM.Models.UserAccount", b =>
                {
                    b.HasOne("APIFurnitureCRM.Models.Staff", "Staff")
                        .WithOne("UserAccount")
                        .HasForeignKey("APIFurnitureCRM.Models.UserAccount", "StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("APIFurnitureCRM.Models.Material", b =>
                {
                    b.Navigation("MaterialOrders");

                    b.Navigation("Specifications");
                });

            modelBuilder.Entity("APIFurnitureCRM.Models.Product", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Specifications");
                });

            modelBuilder.Entity("APIFurnitureCRM.Models.Staff", b =>
                {
                    b.Navigation("MaterialOrders");

                    b.Navigation("Orders");

                    b.Navigation("UserAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
